version: '3'

services:
  client:
    build:
      context: ./client
    depends_on:
      - server
    ports:
      - "8080:80"
    networks:
      - client
      - server
  server:
    build:
      context: ./server
    ports:
      - "8082:8082"
    networks:
      - server
networks:
  client:
  server:

