- name: Install Nginx
  ansible.builtin.apt:
    update_cache: yes
    name: nginx
    state: present

- name: Copy index.html to the Nginx directory
  template:
    src: files/index.html
    dest: /usr/share/nginx/html/

- name: Copy the Nginx configuration file to the host
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
