apiVersion: v1
kind: Service
metadata:
  name: app01-service
spec:
  selector:
    app: app01
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      containerPort: 30000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app01
  template:
    metadata:
      labels:
        app: app01
    spec:
      containers:
        - image: riinavi/app01:latest
          name: app01
          ports:
            - containerPort: 8080
